sudo: required
services:
  - docker

before_install:
  - docker build -t jnanai/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jnanai/client-test npm test -- run

after_success:
  - docker build -t jnanai/multi-client ./client
  - docker build -t jnanai/multi-nginx ./nginx
  - docker build -t jnanai/multi-server ./server
  - docker build -t jnanai/multi-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push jnanai/multi-client
  - docker push jnanai/multi-nginx
  - docker push jnanai/multi-server
  - docker push jnanai/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-692221335950"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_ACCESS_KEY"
