version: '3'
services:
  client:
    image: jnanai/multi-client
    mem_limit: 128m
    hostname: client
  api:
    image: jnanai/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: jnanai/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: jnanai/multi-redis
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
